package dev.api.enums;


public enum Category {
    PROGRAMMING_DEVELOPMENT,
    BUSINESS,
    DESIGN,MARKETING,
    IT_SOFTWARE,
    PERSONALDEVELOPMENT,
    PHOTOGRAPHY,
    LIFESTYLE,
    MUSIC,
    HEALTH_FITNESS
}
